<a href="https://colab.research.google.com/github/kus3093/Pytorch_Tutorial/blob/main/Pytorch_L2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Imports

In [12]:
import numpy as np
import torch


Lists

In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

Numpy Array

In [9]:
np1 = np.random.rand(3,4)
np1

#np2 = np.random.rand(3)
#np2

array([[0.0949354 , 0.34310457, 0.07124311, 0.58732811],
       [0.42524132, 0.1053801 , 0.41258696, 0.69191247],
       [0.72099033, 0.21546088, 0.73479804, 0.63790604]])

In [7]:
np1.dtype

dtype('float64')

Tensors

In [16]:
tensor_2d = torch.randn(3,4)
tensor_2d
## tensor_2d.dtype

torch.float32

In [14]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
##  Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0949, 0.3431, 0.0712, 0.5873],
        [0.4252, 0.1054, 0.4126, 0.6919],
        [0.7210, 0.2155, 0.7348, 0.6379]], dtype=torch.float64)