<a href="https://colab.research.google.com/github/kus3093/Pytorch_Tutorial/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [19]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# Addition Long Hand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [20]:
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

In [7]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [8]:
#Sub Fuctnion
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [9]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
tensor_a

tensor([1, 2, 3, 4])

In [14]:
tensor_b

tensor([5, 6, 7, 8])

In [15]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [16]:
# Exponents / powers
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [18]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [21]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a

tensor([1, 2, 3, 4])

In [23]:
tensor_a = tensor_a + tensor_b

In [24]:
tensor_a

tensor([ 6,  8, 10, 12])

In [25]:
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [26]:
tensor_a

tensor([11, 14, 17, 20])

In [27]:
tensor_a.sub_(tensor_b)

tensor([ 6,  8, 10, 12])

In [28]:
tensor_a

tensor([ 6,  8, 10, 12])